### PR TITLE
Updated OBO

### PR DESCRIPTION
**Pull request by jwest60**
In this branch, I made some changes to the OBO with the help of @bradfordcondon because the previous OBO (i.e. the one on this branch) was filled with wrong relationships, overwritten terms, and duplicate relationships. The whole OBO was just generally pretty buggy, but this has all been fixed with this PR.

Aside from the bug fixes, there were a few general improvements, like the removal of ko00001 from the final OBO, since it was identical to ko00000, which significantly shortened the final OBO. The OBO now also specifies the vocabulary to which each term belongs, which helped fix a bug that was causing relationships to be overwritten, but also makes the OBO a little easier to read.

image

### CODE REVIEW

**Comment by spficklin** [comment]
So it seems this fix has a kegg.obo file in it.  I can see that file getting stale quickly.  Is there a way that the user can update that file or will we be expected to provide periodic updates for it?

**Comment by bradfordcondon** [comment]
thats a good point.  On the other hand i dont like instructing users to generate their own since it involves using hte KEGG API to download each JSON file and running the converter.

We could add CI to re-generate the file every so often?

**Comment by spficklin** [comment]
Okay, fair enough.  This is ready for merging but has some merge conflicts I'm not able to resolve.  If you can fix those then please merge!

**Comment by spficklin** [comment]
Nevermind, I figured out how to merge. I found version numbers in the code that helped me tell the difference.

**Comment by spficklin** [comment]
Hopefully I didn't screw it up.

**Pull request merged**
